// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL2xqb-fofBULXvTnI7j9Q-meBDUrCYiA',
    appId: '1:166924199141:web:56e28a9efca343b05ba00c',
    messagingSenderId: '166924199141',
    projectId: 'recordmmend',
    authDomain: 'recordmmend.firebaseapp.com',
    storageBucket: 'recordmmend.appspot.com',
    measurementId: 'G-NND7QGT5PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpvM80BbEWQ4LW5ymS__fn8r0p_hVX9Ho',
    appId: '1:166924199141:android:a41823d154894e445ba00c',
    messagingSenderId: '166924199141',
    projectId: 'recordmmend',
    storageBucket: 'recordmmend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS80H25d1q-mkm6vmu4NhbiyDFXpFfEXg',
    appId: '1:166924199141:ios:5744928e9b6928c65ba00c',
    messagingSenderId: '166924199141',
    projectId: 'recordmmend',
    storageBucket: 'recordmmend.appspot.com',
    iosClientId: '166924199141-k5hvp6cjsjtuemovhbvirol673eev96a.apps.googleusercontent.com',
    iosBundleId: 'com.example.recordmmend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS80H25d1q-mkm6vmu4NhbiyDFXpFfEXg',
    appId: '1:166924199141:ios:5744928e9b6928c65ba00c',
    messagingSenderId: '166924199141',
    projectId: 'recordmmend',
    storageBucket: 'recordmmend.appspot.com',
    iosClientId: '166924199141-k5hvp6cjsjtuemovhbvirol673eev96a.apps.googleusercontent.com',
    iosBundleId: 'com.example.recordmmend',
  );
}
